modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="anam"
version="1.0.0"
displayName="Aitor's Nether Additions Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="imaca, MCreator"

[[dependencies.anam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




